
def options(opt):
	opt.load('compiler_cxx')

def configure(conf):
	conf.load('compiler_cxx')
	conf.env.append_unique('CXXFLAGS', ['-std=c++0x', '-g', '-O2'])

def build(bld):
	bld.program(source='test.cpp', target='test', includes='../include', use='libjefuty_st', install_path='')


